import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

const CODEBASE_CONTEXT = `
You are an expert code analyst for the Claude Code (claude_code_Template) open-source project.
You have performed a deep analysis of the entire 182,039-line TypeScript codebase (1,884 files).

## ARCHITECTURE OVERVIEW
Claude Code is a sophisticated multi-agent CLI framework built with React/Ink (terminal UI) and TypeScript.

### Entry Point
- **src/main.tsx** (4,683 lines) — Commander.js CLI + React/Ink renderer, orchestrates all subsystems

### Core Engine
- **QueryEngine.ts** — LLM orchestration, dispatches tool calls, manages conversation loop
- **Tool.ts** — Base Tool interface: { name, description, inputJSONSchema, execute() }
- **Task.ts** — Task polymorphism: 6 types (local_bash, local_agent, remote_agent, in_process_teammate, local_workflow, dream)
- **AppState.tsx** — Central reactive state (session, messages, tasks, permissions)

### 40+ Built-in Tools (src/tools/)
File ops: FileReadTool, FileEditTool, FileWriteTool, GlobTool, GrepTool, NotebookEditTool
Shell: BashTool, PowerShellTool, REPLTool
Web: WebFetchTool, WebSearchTool
Agents: AgentTool (spawns async sub-agents), SkillTool
Tasks: TaskCreateTool, TaskGetTool, TaskListTool, TaskUpdateTool, TaskStopTool, TaskOutputTool
MCP: MCPTool, ListMcpResourcesTool, ReadMcpResourceTool, McpAuthTool
Planning: EnterPlanModeTool, ExitPlanModeTool, EnterWorktreeTool, ExitWorktreeTool
Scheduling: CronCreateTool, CronDeleteTool, CronListTool, RemoteTriggerTool
Team: TeamCreateTool, TeamDeleteTool, SendMessageTool
Other: TodoWriteTool, AskUserQuestionTool, ToolSearchTool, BriefTool, ConfigTool

### Services Layer (src/services/ — 21 modules)
- api/ — Anthropic Claude SDK integration, cost tracking, retry logic
- mcp/ — MCP server management, auth, dynamic tool generation
- autoDream/ — Background memory consolidation (Orients→Gathers→Consolidates→Prunes)
- oauth/ — GitHub/Google OAuth providers
- compact/ — Message history compaction & snipping
- lsp/ — Language Server Protocol for code analysis
- analytics/ — GrowthBook feature gates, telemetry, A/B testing
- SessionMemory/, extractMemories/, teamMemorySync/ — Memory systems

### Multi-Agent Orchestration
- **coordinator/coordinatorMode.ts** — Multi-worker swarm, spawns AgentTool workers, team communication
- **assistant/KAIROS** — Proactive background agent watching for system events (feature-gated)
- **services/autoDream** — Memory consolidation as DreamTask

### Bridge Layer (src/bridge/ — 32 files)
WebSocket IDE integration for VS Code and JetBrains:
- bridgeApi.ts, bridgeMessaging.ts, bridgeUI.ts — core protocol
- replBridge.ts, remoteBridgeCore.ts — REPL integration
- JWT-secured sessions, file attachments, permission callbacks

### Security Architecture
- Permission Modes: default (ask), auto (allow), bypass_permissions, plan_mode
- Tool-level rules: alwaysAllow, alwaysDeny, alwaysAsk
- OAuth, keychain (macOS), MDM policies, JWT bridge auth
- Undercover mode: hides internal codenames (Tengu=Claude Code, Capybara=model codename)

### Buddy System (src/buddy/)
Deterministic tamagotchi companion: 18 species × rarity tiers × 5 stats
PRNG seeded from userId hash (Mulberry32) → consistent identity per user
ASCII art animations, soul generated by Claude and cached in config

### Key Design Patterns
1. Feature Gates: Dead-code elimination via GrowthBook feature flags
2. Lazy Imports: Circular dependency breaking via require() in closures
3. Tool Registration: Central tools.ts map, QueryEngine dispatches by name
4. Task Polymorphism: Base Task with kill(), 6 concrete implementations
5. Permission Context Injection: Immutable context passed through query pipeline
6. Message Normalization: SDK ↔ internal type bidirectional conversion
7. Async Task Output Streaming: Per-task output files with offset tracking

### CLI (70+ commands in src/commands/)
Session: session, resume, rewind, teleport
Code: review, diff, export, clear
Config: model, config, settings, theme, keybindings, permissions
Features: plan, memory, tasks, agents, skills, plugin, mcp, chrome
Dev: doctor, debug-tool-call, heapdump, perf-issue, costs, stats
Auth: login, logout, oauth-refresh, install-github-app, install-slack-app

### Build
- Bundler: Bun (tree-shaking via feature gates)
- Language: TypeScript strict mode
- Main entry: 785KB minified
- Source maps: shipped (enabled open-source analysis)

When asked about a specific file or folder, draw on this analysis to give detailed explanations.
When asked to "find bugs", identify common patterns: missing error handling, type coercions with "as any", potential race conditions in async task streams, security concerns in bridge JWT handling.
When asked to "explain design patterns", reference the 9 core patterns above with concrete examples.
When asked to "summarize a folder", give a role-based summary of what that subsystem does in the broader architecture.
Always be specific, cite file paths, line counts, and type names from the analysis.
`;

export async function POST(req: NextRequest) {
  try {
    const { message, file, action } = await req.json();

    let userMessage = message;
    if (action === "summarize_folder" && file) {
      userMessage = `Please give a comprehensive summary of the "${file}" folder/module. What does it do? What are the key files? How does it fit in the overall architecture? What design patterns does it use?`;
    } else if (action === "find_bugs" && file) {
      userMessage = `Analyze "${file}" for potential bugs, security issues, or code quality problems. Look for: missing error handling, type safety issues (any casts), race conditions, security vulnerabilities, missing validation. Be specific with file paths and patterns.`;
    } else if (action === "explain_pattern" && file) {
      userMessage = `Explain the design pattern used in "${file || "this codebase"}". What pattern is it? Why was it chosen? What are the trade-offs? Show how it connects to other parts of the system.`;
    } else if (action === "generate_docs" && file) {
      userMessage = `Generate comprehensive documentation for "${file}". Include: purpose, public API/interface, parameters, return types, usage examples, edge cases, and how it integrates with other modules.`;
    }

    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash",
      systemInstruction: CODEBASE_CONTEXT,
    });

    const result = await model.generateContentStream(userMessage);

    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        for await (const chunk of result.stream) {
          const text = chunk.text();
          if (text) {
            controller.enqueue(encoder.encode(`0:${JSON.stringify(text)}\n`));
          }
        }
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "X-Vercel-AI-Data-Stream": "v1",
      },
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Analysis failed";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
